export type ChainId = 'BTC' | 'ETH' | 'SOL' | 'BNB' | 'TRX' | 'DOGE' | 'LTC' | 'BCH' | 'AVAX' | 'POL';

export interface ChainConfig {
  id: ChainId;
  name: string;
  symbol: string;
  coinType: number; // SLIP-0044 coin type
  curve: 'secp256k1' | 'ed25519';
  derivationPath: string;
  addressPrefix: string;
  addressFormatName: string;
  iconBg: string;
  badgeColor: string;
  defaultPriceUsd: number;
  decimals: number;
  explorerUrl: string;
  coingeckoId: string;
  descriptionTh: string;
  descriptionEn: string;
}

export const SUPPORTED_MULTI_CHAINS: ChainConfig[] = [
  {
    id: 'BTC',
    name: 'Bitcoin',
    symbol: 'BTC',
    coinType: 0,
    curve: 'secp256k1',
    derivationPath: "m/84'/0'/0'/0/0",
    addressPrefix: 'bc1q',
    addressFormatName: 'Native SegWit (Bech32)',
    iconBg: 'from-amber-500 to-orange-600',
    badgeColor: 'bg-amber-500/20 text-amber-300 border-amber-500/40',
    defaultPriceUsd: 94850.00,
    decimals: 8,
    explorerUrl: 'https://mempool.space/address/',
    coingeckoId: 'bitcoin',
    descriptionTh: 'บล็อกเชนต้นกำเนิด ราชาแห่งสินทรัพย์ดิจิทัล (PoW)',
    descriptionEn: 'The original decentralized digital gold (Proof of Work)',
  },
  {
    id: 'ETH',
    name: 'Ethereum',
    symbol: 'ETH',
    coinType: 60,
    curve: 'secp256k1',
    derivationPath: "m/44'/60'/0'/0/0",
    addressPrefix: '0x',
    addressFormatName: 'EVM Standard (ERC-20/EIP-55)',
    iconBg: 'from-blue-600 to-indigo-700',
    badgeColor: 'bg-blue-500/20 text-blue-300 border-blue-500/40',
    defaultPriceUsd: 2680.00,
    decimals: 18,
    explorerUrl: 'https://etherscan.io/address/',
    coingeckoId: 'ethereum',
    descriptionTh: 'ผู้นำเครือข่าย Smart Contract และ EVM DeFi ระดับโลก',
    descriptionEn: 'Leading programmable smart contract and EVM ecosystem',
  },
  {
    id: 'SOL',
    name: 'Solana',
    symbol: 'SOL',
    coinType: 501,
    curve: 'ed25519',
    derivationPath: "m/44'/501'/0'/0'",
    addressPrefix: 'Base58',
    addressFormatName: 'Solana Ed25519 Pubkey',
    iconBg: 'from-purple-600 to-emerald-500',
    badgeColor: 'bg-purple-500/20 text-purple-300 border-purple-500/40',
    defaultPriceUsd: 188.50,
    decimals: 9,
    explorerUrl: 'https://solscan.io/account/',
    coingeckoId: 'solana',
    descriptionTh: 'บล็อกเชนความเร็วสูง TPS หลักหมื่น ค่าธรรมเนียมเสี้ยวสตางค์',
    descriptionEn: 'High-throughput Layer 1 with sub-second finality',
  },
  {
    id: 'BNB',
    name: 'BNB Smart Chain',
    symbol: 'BNB',
    coinType: 714,
    curve: 'secp256k1',
    derivationPath: "m/44'/60'/0'/0/0",
    addressPrefix: '0x',
    addressFormatName: 'BEP-20 (EVM Compatible)',
    iconBg: 'from-yellow-500 to-amber-600',
    badgeColor: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/40',
    defaultPriceUsd: 645.00,
    decimals: 18,
    explorerUrl: 'https://bscscan.com/address/',
    coingeckoId: 'binancecoin',
    descriptionTh: 'เครือข่าย EVM ของระบบนิเวศ Binance รวดเร็วและค่าแก๊สต่ำ',
    descriptionEn: 'Binance Smart Chain ecosystem with low gas fees',
  },
  {
    id: 'TRX',
    name: 'TRON',
    symbol: 'TRX',
    coinType: 195,
    curve: 'secp256k1',
    derivationPath: "m/44'/195'/0'/0/0",
    addressPrefix: 'T',
    addressFormatName: 'TRC-20 Base58Check (T-Prefix)',
    iconBg: 'from-red-500 to-rose-700',
    badgeColor: 'bg-rose-500/20 text-rose-300 border-rose-500/40',
    defaultPriceUsd: 0.245,
    decimals: 6,
    explorerUrl: 'https://tronscan.org/#/address/',
    coingeckoId: 'tron',
    descriptionTh: 'เครือข่ายโอนยอดนิยมอันดับ 1 ของเหรียญ USDT (TRC-20)',
    descriptionEn: 'Dominant transfer layer for stablecoins worldwide (TRC-20)',
  },
  {
    id: 'DOGE',
    name: 'Dogecoin',
    symbol: 'DOGE',
    coinType: 3,
    curve: 'secp256k1',
    derivationPath: "m/44'/3'/0'/0/0",
    addressPrefix: 'D',
    addressFormatName: 'Legacy P2PKH (D-Prefix)',
    iconBg: 'from-amber-400 to-yellow-500',
    badgeColor: 'bg-yellow-400/20 text-yellow-200 border-yellow-400/40',
    defaultPriceUsd: 0.265,
    decimals: 8,
    explorerUrl: 'https://dogechain.info/address/',
    coingeckoId: 'dogecoin',
    descriptionTh: 'เหรียญมีมและสกุลเงินยอดนิยมชุมชนโลก Scrypt PoW',
    descriptionEn: 'The community favorite peer-to-peer Scrypt cryptocurrency',
  },
  {
    id: 'LTC',
    name: 'Litecoin',
    symbol: 'LTC',
    coinType: 2,
    curve: 'secp256k1',
    derivationPath: "m/84'/2'/0'/0/0",
    addressPrefix: 'ltc1q',
    addressFormatName: 'Litecoin Native SegWit (MWEB Ready)',
    iconBg: 'from-slate-400 to-blue-500',
    badgeColor: 'bg-slate-400/20 text-slate-200 border-slate-400/40',
    defaultPriceUsd: 112.50,
    decimals: 8,
    explorerUrl: 'https://blockchair.com/litecoin/address/',
    coingeckoId: 'litecoin',
    descriptionTh: 'เงินดิจิทัลคู่ขนาน Bitcoin บล็อก 2.5 นาที รองรับ MWEB',
    descriptionEn: 'Silver to Bitcoin gold, fast 2.5m block confirmation',
  },
  {
    id: 'BCH',
    name: 'Bitcoin Cash',
    symbol: 'BCH',
    coinType: 145,
    curve: 'secp256k1',
    derivationPath: "m/44'/145'/0'/0/0",
    addressPrefix: 'bitcoincash:q',
    addressFormatName: 'CashAddr Base32',
    iconBg: 'from-emerald-500 to-green-600',
    badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40',
    defaultPriceUsd: 385.50,
    decimals: 8,
    explorerUrl: 'https://blockchair.com/bitcoin-cash/address/',
    coingeckoId: 'bitcoin-cash',
    descriptionTh: 'Peer-to-peer Electronic Cash บล็อก 32MB โอนไว',
    descriptionEn: 'On-chain scaling peer-to-peer electronic cash',
  },
  {
    id: 'AVAX',
    name: 'Avalanche C-Chain',
    symbol: 'AVAX',
    coinType: 9000,
    curve: 'secp256k1',
    derivationPath: "m/44'/60'/0'/0/0",
    addressPrefix: '0x',
    addressFormatName: 'Avalanche EVM C-Chain',
    iconBg: 'from-red-600 to-rose-600',
    badgeColor: 'bg-red-500/20 text-red-300 border-red-500/40',
    defaultPriceUsd: 32.40,
    decimals: 18,
    explorerUrl: 'https://snowtrace.io/address/',
    coingeckoId: 'avalanche-2',
    descriptionTh: 'ระบบฉันทามติ Avalanche Consensus เร็วเสี้ยววินาที',
    descriptionEn: 'Blazing fast Avalanche consensus and Subnet scalability',
  },
  {
    id: 'POL',
    name: 'Polygon Ecosystem',
    symbol: 'POL',
    coinType: 966,
    curve: 'secp256k1',
    derivationPath: "m/44'/60'/0'/0/0",
    addressPrefix: '0x',
    addressFormatName: 'Polygon EVM PoS / zkEVM',
    iconBg: 'from-purple-500 to-indigo-600',
    badgeColor: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/40',
    defaultPriceUsd: 0.48,
    decimals: 18,
    explorerUrl: 'https://polygonscan.com/address/',
    coingeckoId: 'matic-network',
    descriptionTh: 'โครงข่าย Layer 2 / zkEVM สเกลระบบ Ethereum สากล',
    descriptionEn: 'Aggregated blockchain Layer 2 scaling Ethereum',
  },
];
